---
title: "Formación San Juan (19)"
---

<div style="text-align: justify">

## Calizas.

La Formación San Juan (Kobayashi, 1937, enmend. Amos, 1954) está integrada por calizas y dolomías de color gris claro a gris oscuro en bancos estratificados de 0,1 a 4 m de potencia, con presencia de nódulos de pedernal estratificados en algunos casos. Se depositó en ambiente marino poco profundo, de plataforma. El contenido fosilífero es abundante, sobre todo en los niveles superiores. La asociación fosilífera corresponde a la Zona Proetiella tellecheai. En los niveles inferiores se destacan Maclurites avellanedaes, Orthis sp, Orthis caligramma y Proetiella tellecheai. El espesor es de 400 metros. No se conoce la base de esta formación. Los afloramientos de la Formación San Juan se localizan en el flanco oriental de la sierra de La Invernada. En la base la relación es por falla inversa con la Formación Punta Negra, mientras que su techo es discordante con la Formación Corralito. Los afloramientos en la hoja Rodeo son los más occidentales de esta unidad calcárea, más extendida en las Precordilleras Central y Oriental.

<div/>
