---
title: "Grupo Choyoi (4)"
---

<div style="text-align: justify">

## Conglomerados, areniscas, pelitas, aglomerados, ignimbritas andesíticas a dacíticas, basaltos, andesitas, tobas

En la región de Castaño y en el borde oriental de los cordones de Olivares y de Colangüil afloran volcanitas del Grupo Choiyoi (Yrigoyen, 1972). Los antecedentes más antiguos referentes a la existencia de pórfidos cuarcíferos en Cordillera Frontal se remontan a Stelzner (1885). Groeber (1918) denominó Serie Porfirítica Supratriásica a este conjunto, al que luego modificó por el de Choiyoilitense (Groeber, 1946, 1947). Esta unidad fue denominada Formación Choiyoi por Rolleri y Criado Roque (1969). Al oeste del valle de Los Patos Norte afloran vulcanitas que en el territorio chileno se asignaron a la Formación Pastos Blancos (Thiele, 1964) de edad permotriásica, equivalentes al Grupo Choiyoi. En el ámbito de la Hoja Castaño Viejo, Rodríguez Fernández et al. (1996) definieron al Grupo Choiyoi como un conjunto volcanosedimentario situado entre discordancias, que ocupa la base de la secuencia extensional. Dentro de este grupo separaron tres formaciones: Castaño, La Chilca y Las Pircas.

En la región del río Castaño se han mapeado las distintas unidades del Grupo Choiyoi, mientras que hacia el norte se ha representado el Grupo Choiyoi en forma indiferenciada.
Los depósitos del Grupo Choiyoi se han desarrollado en un régimen extensional de tipo rifting. Los bloques elevados se encuentran al este y norte, donde los espesores son menores (área del plutón Tocota). Al oeste los espesores aumentan hasta 2500 y 3000 metros.

Determinaciones por Rb/Sr de las ignimbritas andesíticas y diques asociados se alinean en una isócrona de 256 ± 6 Ma. (Shaw et al., 1990). Dataciones K/Ar realizadas en rocas de la Formación La Chilca, cerca del contacto con el Grupo Melchor, dieron 243,8 ± 5 Ma. y 234, 6 ± 4,5 Ma. (Rodríguez Fernández et al., 1996). Es decir que la edad del Grupo Choiyoi es pérmica inferior a triásica superior. Rocas volcánicas aflorantes en las cabeceras del arroyo Agua Negra han sido datadas por la empresa que tuvo a cargo la ejecución de la hoja geológica a escala 1:100.000, 3169-2, Paso de Agua Negra. Una de las dataciones dio 315 ± 15 Ma. y otra 287 ± 15 Ma., es decir edad carbonífera a pérmica inferior.El espesor total de la unidad es estimado en 4500 a 5000 metros.

Sato y Llambías (1993) consideraron a las rocas del Grupo Choiyoi como equivalentes efusivos de las del batolito de Colangüil, sobre la base de consideraciones geoquímicas y edad. Rodríguez Fernández et al. (1996) estimaron que las unidades ígneas y volcánicas referidas son equivalentes. El Grupo Choiyoi se habría depositado en el hemigraben de Castaño, mientras se producía la intrusión de las rocas plutónicas del batolito de Colangüil en el horst de las Tranquitas, a pocos kilómetros de la superficie.

Según Llambías et al. (1990) en el cordón de Colangüil el Grupo Choiyoi está integrado por dos secciones: una inferior sedimentaria y una sección superior constituida predominantemente por ignimbritas andesíticas a dacíticas. El pasaje entre ambas secciones es transicional. En general, la sección inferior falta, asentándose las ignimbritas en forma discordante sobre las unidades más antiguas. La sección sedimentaria tiene sus mejores afloramientos entre las quebradas de Mondaca y Conconta. El espesor en estas localidades es de 200 m, mientras que en la quebrada de Romo es de 300 m. La secuencia se inicia con un conglomerado, en parte brechoso, altamente resistente a la erosión, constituido por clastos de hasta 20 cm de diámetro y mátrix arenosa.

Los clastos están compuestos por areniscas, andesitas y cuarzo lechoso y son subredondeados a subangulosos. Le suceden areniscas cuarzo feldespáticas de grano mediano a grueso hasta sabulíticos, grises claros, que contienen intercalaciones conglomerádicas similares a las descritas. En ella se han hallado restos de vegetales muy mal conservados. Localmente contienen intercalaciones de bancos pelíticos oscuros. Hacia arriba pasan a aglomerados volcánicos con abundantes clastos de andesitas alteradas. Esta zona de transición hacia los mantos ignimbríticos andesíticos es del orden de los 100 m e indica el comienzo de la fase eruptiva. La sección inferior sedimentaria también aflora en el arroyo de Chita, se trata de un conglomerado petromíctico compuesto por clastos de rocas volcánicas, plutónicas (granitos) y sedimentarias. La sección superior, la más extensa y de mayor espesor, está constituida principalmente por ignimbritas andesíticas a dacíticas. Predominan los aglomerados en los niveles inferiores. Se han medido hasta 400 m en la quebrada de Colangüil. Son de color gris verdoso oscuro. Están compuestas por cristales de plagioclasa y anfíboles (escaso piroxeno) y están frecuentemente propilitizadas. En la quebrada de Mondaca se observan intercalaciones de potentes capas de basaltos con disyunción columnar, andesitas con alteración propilítica y silicificación y tobas cristalinas líticas andesíticas. La sección inferior es equivalente a la Formación Castaño, mientras que la parte superior se corresponde con la Formación La Chilca.

<div/>
