---
title: "Formación Las Flores (26b)"
---

<div style="text-align: justify">

## Arcilitas, limolitas y areniscas.

Los depósitos de la Formación Las Flores están distribuidos en la depresión de Villa Nueva hasta la depresión de Angualasto, ocupando la parte central del valle de Iglesia., localizándose desde el oeste del cerro Negro hasta la localidad de Cuesta del Viento y desde el oeste de Pismanta hasta Colangüil. Esta unidad está constituida por una sucesión de arcilitas, limolitas bien estratificadas en gruesos bancos muy compactos y areniscas finas de tonos rojizos, castaños y amarillos claro, con intercalaciones de yeso laminar.

Johnson et al. (1987) describieron la secuencia terciaria que aflora entre Cuesta del Viento y la localidad de Rodeo, dividiéndola en dos partes que reflejan dos ambientes de depositación. La parte inferior se formó en un sistema de ríos proveniente de un centro volcánico. Los depósitos son una combinación de sedimentos fluviales de importantes cursos de agua y tobas (ash flow) con clastos de pómez de hasta 4 centímetros. La parte superior se formó en una planicie suave con algunos intervalos lacustres. La secuencia contiene capitas de yeso y calizas lacustres.

En las cercanías de Angualasto, Beer et al. (1990), Re y Barredo (1993) y Re (1994) describieron secuencias granodecrecientes de 280 m de espesor correspondientes a la Formación Las Flores, compuestas por varios ciclos interrumpidos por otros, con estructuras sedimentarias de corte y relleno, estratificación cruzada en artesa y cruzada planar. Vincularon estos depósitos a un ambiente de planicies arenosas correspondientes a facies distales de abanicos aluviales, con intercalaciones de areniscas y conglomerados correspondientes a flujos canalizados de un sistema de cursos entrelazados (braided) y pelitas arenosas finas, relacionadas con planicies de inundación. Las intercalaciones de yeso indicarían facies lagunares o de playa lake.

Los depósitos de esta unidad están dispuestos en discordancia sobre unidades del Paleozoico y a su vez cubiertos en discordancia angular por sedimentos cuaternarios. Se dispone en forma concordante sobre la Formación Lomas del Campanario. El espesor de la Formación Las Flores se estima en más de 600 metros.

Re y Barredo (1993) y Re (1994) dataron las secuencias de la Formación Las Flores en 11,2 ± 0,5 y 8,2 ± 0,2 Ma. por el método Ar/Ar y establecieron tasas de sedimentación que revelan un incremento paulatino que podría estar relacionado con el ascenso relativo del área de aporte (Beer et al., 1990).

De acuerdo con las dataciones radimétricas, la edad de esta unidad es Mioceno medio a superior.

<div/>
