---
title: "Fm. Granitoides Tocota (2)"
---

<div style="text-align: justify">

## Tonalitas, granitos, granodioritas y microgranitos

El plutón más meridional del batolito de Colangüil es el plutón Tocota. Según Rodríguez Fernández et al. (1996), representa un plutón plurifacial y plurintrusivo alargado en dirección N- S y constituido por tres grupos litológicos diferentes. Estos corresponden a tres pulsos intrusivos sucesivos, que a grandes rasgos confieren al conjunto batolítico una zonación irregular centrípeta, con las facies más básicas y cronológicamente más antiguas ocupando las partes externas. En función de las relaciones de intrusión, se pueden diferenciar, de más antigua a más moderna, las siguientes unidades plutónicas: Tonalita del Leoncito, Granito de la Fragüita y Microgranitos rosados, además de un conjunto de diques y filones relacionados. Todos los grupos litológicos presentan como rasgos comunes la ausencia casi absoluta de fábricas deformativas penetrativas, estando solo afectados por las fallas andinas, hecho que sugiere que sus emplazamientos tuvieron lugar en condiciones permitidas, al final de la orogénesis Gondwánica (Fase Sanrafaélica) bajo un régimen de deformación postorogénico extensional.

La Tonalita del Leoncito es un conjunto de dioritas, granodioritas y tonalitas que constituyen las rocas más antiguas del batolito y se disponen en las periferias del mismo. Presentan procesos de alteración (propilítica y potásica generalmente) y en todos los casos intruyen con carácter neto a las rocas sedimentarias de la Formación Agua Negra. La presencia de enclaves más básicos sugiere procesos de mezcla imperfecta de magmas y un carácter híbrido de los líquidos a partir de los cuales cristalizaron estas rocas.
El Granito de la Fragüita intruye en las rocas de la Tonalita del Leoncito en contacto con las cuales presenta un borde de enfriamiento de 100 a 150 m de espesor. También presenta enclaves microgranudos semejantes a los descritos en el caso anterior.
Los Microgranitos rosados son un conjunto de cuerpos de geometría lacolítica, de dimensiones variables (entre 10 m a más de 1 km) y diques que intruyen a las rocas descritas anteriormente y a las sedimentitas paleozoicas. Son rocas de grano muy fino, color rosado, con menos del 5 % de melanocratos y abundancia de cavidades miarolíticas rellenas de turmalina, cuarzo y feldespato. Los rasgos descritos representan un magma residual muy diferenciado y saturado en agua.

La edad de las rocas que conforman el plutón Tocota ha sido establecida por Linares y Llambías (1974) en la quebrada de Tocota en 283 ± 15 Ma. Una datación K/Ar realizada por el INGEIS durante el levantamiento de la hoja Castaño Viejo en el Granito de la Fragüita arrojó una edad de 299 ± 10 Ma.


<div/>
