---
title: "Grupo Angualasto (22)"
---

<div style="text-align: justify">

## Areniscas, limolitas, conglomerados.

Las sedimentitas carboníferas que afloran en la zona de Angualasto han recibido distintas denominaciones según diversos autores. Polanski (1970) creó el Grupo Quebrada del Volcán, compuesto por sedimentitas de edad carbonífera inferior, superior y pérmica. Furque (1963) distinguió tres cuencas carboníferas en el levantamiento de la Hoja Guandacol. La cuenca occidental, llamada Malimán, comprende los afloramientos en el área de la Hoja Rodeo. Los depósitos carboníferos de esta cuenca fueron agrupados en la Formación Volcán, constituida por bancos de areniscas y limolitas verde claro a oscuro con restos marinos.
Scalabrini Ortiz (1970) denominó Formación Malimán a la parte inferior de la unidad y Formación Cortaderas a la parte superior.

Limarino y Césari (1992) definieron el Grupo Angualasto, integrando las formaciones Malimán, Cortaderas y El Ratón, esta última aflorante en Calingasta, a efectos de facilitar la cartografía. Consideraron a la Formación Cortaderas esencialmente dentro del Carbonífero inferior, lo que incrementó la importancia de la sedimentación carbonífera, y modificaron las correlaciones estratigráficas. La edad carbonífera inferior de la Formación Cortaderas está corroborada por el hallazgo de una rica asociación palinológica. Con respecto a la discordancia erosiva señalada por Scalabrini Ortiz (1970) entre las formaciones Malimán y Cortaderas, Limarino y Césari (1992) consideraron posible que las variaciones correspondan a cambios faciales antes que a erosión.

La Formación Malimán está compuesta por areniscas y limolitas de color verde claro, areniscas grises y subgrauvacas. Se sitúa en forma discordante sobre la Formación Chavela del Devónico medio a superior y la relación del techo es discordante. Tiene un espesor de 1188 metros.
La Formación Cortaderas constituye un conjunto de 1160 m de sedimentitas agrupadas en tres miembros: el inferior, compuesto por un conglomerado gris verdoso oscuro e interpretado como depósito de piedemonte; el medio, integrado por areniscas gris verdosas con estratificación entrecruzada y limolitas con restos vegetales, depositados en un ambiente fluvial de llanura de inundación; y el superior con limolitas y ortoconglomerados verdosos, que representan depósitos fluviales.

En la quebrada El Carrizal (Figura 9) se observa una secuencia de areniscas finas inclinando 45° al este, de color castaño verdoso, micáceas, con presencia de ondulitas y con intercalaciones de lutitas. Esta secuencia es estrato y grano decreciente y tiene cuerpos lenticulares de grano más grueso intercalados. Por encima, en forma discordante, se apoya un conglomerado mátrix sostén con clastos redondeados y polimícticos. Se destaca la presencia de clastos de cuarzo muy redondeados. Esta serie es grano decreciente y pasa hacia arriba a lutitas negras laminadas. Se interpreta que estas sedimentitas comprenden el miembro de areniscas grises del techo de la Formación Malimán (Scalabrini Ortiz, 1972) y el miembro de conglomerados grises verdoso oscuro, según el mismo autor, que constituiría la base de la Formación Cortaderas.

La edad del Grupo Angualasto es carbonífera inferior, sobre la base de los elementos florísticos y faunísticos determinados en la Formación Malimán y en la flora hallada en la Formación Cortaderas, sin descartarse la posibilidad que los depósitos cuspidales de esta última unidad pasen al Carbonífero superior (Limarino y Césari, 1992).

<div/>
