---
title: "Grupo Olivares (15)"
---

<div style="text-align: justify">

## Basaltos, andesitas, tobas, brechas, aglomerados, dacitas.

Esta unidad fue descripta en las nacientes del arroyo de Chita por Bastías (1991), quien mencionó secuencias volcanosedimentarias que integró al Grupo Olivares (Minera TEA, 1968; Aparicio, 1984, enmend. Bastías, 1991). Minera TEA (1968) denominó Formación Basáltica de Olivares a la serie volcánica del Terciario superior descripta en éste ítem.
Los afloramientos alcanzan su máxima expresión en el macizo de Olivares, extendiéndose hasta el arroyo del Agua Negra por el norte, hasta la cordillera de Lucho por el sur. El espesor es de alrededor de 1000 metros.

En el Grupo Olivares se han diferenciado las formaciones Poposa, Barrancas de Olivares y Volcancitos (Bastías, 1991). La Formación Poposa está representada por lavas de composición andesítica que afloran en la quebrada homónima. La posición de estas volcanitas es subhorizontal y tienen unos 200 m de espesor. La Formación Barrancas de Olivares está integrada por coladas andesíticas grises, mantos tobáceos estratificados de color verde claro, brechas volcánicas con clastos de andesitas y aglomerados volcánicos. El perfil de esta unidad fue descripto por Charchaflié (1994) en las nacientes de los arroyos de Chita (500 m) y Tocota (250 m). La Formación Volcancitos está constituida por andesitas verdosas que integran los cerros de mayor altura, como Puntudo, Ismael y Volcán de los Porteños. Estas unidades presentan variaciones faciales locales, por lo que están asociadas a las efusiones de los aparatos volcánicos próximos.

Al oeste de la región de Castaño Viejo, el Grupo Olivares se sitúa en forma discordante sobre todas las unidades anteriores. Está constituido por un conjunto volcanosedimentario de basaltos andesíticos organizados en coladas masivas, subhorizontales, con un horizonte de aglomerados volcánicos en la base, intruido por numerosos cuerpos dacíticos a riodacíticos, con una potencia de 300 metros.

En el cordón de Olivares, el Grupo Olivares yace en forma discordante sobre las unidades más antiguas (Formación Agua Negra, Grupo Choiyoi, Intrusivo Las Pircas y Grupo Melchor).
La edad del Grupo Olivares se ha interpretado que debe corresponder al intervalo entre el Mioceno medio y el Plioceno (Rodríguez Fernández et al., 1996).
<div/>

