---
title: "Formación Yerba Loca (20a)"
---

<div style="text-align: justify">

## Basaltos, pillow lavas, gabros, rocas ultrabásicas.

Los cuerpos basálticos concordantes se hacen más frecuentes y más potentes hacia el techo de la Formación Yerba Loca, donde también se intercalan cuerpos de pillow lavas y basaltos columnares (Cuesta del Viento). En los lugares donde estos cuerpos básicos dominan sobre las sedimentitas se les ha mapeado como una unidad diferenciada (20a). Esencialmente existen dos cuerpos importantes: uno en la zona de Cuesta del Viento (Figura 6) y el otro en el extremo norte de la sierra del Tigre.

En los trabajos de Stappenbeck (1910) y Keidel (1922) sobre la Precordillera de San Juan y Mendoza se cita la presencia de rocas máficas y ultramáficas que afloran en la Precordillera Occidental. Borrello (1968, 1969) destacó el carácter ofiolítico de estas rocas. Furque (1979) describió estas unidades y Cortelezzi et al. (1982) realizaron el estudio petrológico de las mismas, en tanto que Kay et al. (1984) destacaron su carácter oceánico. Haller y Ramos (1984) las consideraron como ofiolitas, en función de sus características litológicas y estructurales.El espesor de éstos cuerpos varía de 50 cm hasta 0,60 metros.

En el sector de Cuesta del Viento, Haller y Ramos (1984) describieron una secuencia de 495 m, inclinada en alto ángulo al oeste, integrada por cuerpos máficos con diques de wehrlita, lavas basálticas con estructuras en almohadilla y lavas de basalto con disyunción columnar e intruidas por filones gábricos de grano fino a grueso de 8 a 15 m de espesor. Las coladas basálticas tienen potencias de 4 a 20 metros. Más al este y separadas por falla observaron una secuencia de grauvacas de grano mediano a grueso de la facies sedimentaria de la Formación Yerba Loca, en la que se emplazan mantos de basalto, filones de gabro y filones concordantes de wehrlita. El conjunto está deformado y plegado con vergencia al oeste (Heim, 1952). En la sierra del Tigre, en el corte del camino del Puntudo, fue descripta una secuencia que de oeste a este comprende coladas basálticas, grauvacas grises oscuras a verdosas con intercalaciones de mantos basálticos, lavas con estructura en almohadillas y cuerpos de gabros concordantes con la estratificación de las grauvacas. Todo este conjunto está inclinando hacia el oeste y las rocas máficas y ultramáficas fueron interpretadas como pertenecientes a una secuencia ofiolítica (Haller y Ramos, 1984).

Según Cortelezzi et al. (1982) y Furque (1983), los afloramientos de basalto son generalmente de geometría tabular, concordantes con las pelitas, psamitas y calizas de las formaciones La Invernada y Yerba Loca, aunque también existen cuerpos discordantes (diques) intruyendo dichas formaciones. Según estos mismos autores, el afloramiento más importante es el localizado en el cerro Bayo (sierra de La Invernada). Es un basalto de color negro a marrón oscuro, con textura porfírica, pasta muy fina, con escasos fenocristales de plagioclasa básica y piroxenos y se encuentra generalmente alterado, propilitizado y serpentinizado. Las plagioclasas están generalmente argilitizadas y carbonatizadas.

También se han observado afloramientos de cuerpos basálticos discordantes en la sierra de La Crucecita. Se trata de diques formados por abundantes plagioclasas y mafitos intercrecidos. Todos los minerales están fuertemente alterados. Las plagioclasas están argilitizadas y carbonatizadas. El mafito aparece totalmente cloritizado y con incipiente carbonatización.
Cuerpos integrados por pillow lavas se encuentran en Cuesta del Viento y región central y norte de la sierra del Tigre (Figura 7). El primero es el más importante, habiéndose acumulado por espacio de unos 300 m en sentido norte- sur y de 800 a 1000 m en sentido este – oeste, en tanto que en el extremo norte de la sierra del Tigre se extienden por unos 800 m en la cumbre de dicha sierra, con un ancho aproximado de 100 metros (Cortelezzi et al., 1982). Se considera que estos derrames submarinos ocurrieron durante la sedimentación de los últimos niveles lutíticos de la formación, con espesores de entre 30 y 50 metros.

Filones capa de gabros, en general de forma tabular, intruyen rocas de la Formación Yerba Loca (grauvacas y basaltos). El espesor es de 8 a 15 metros. Las rocas de caja se encuentran levemente metamorfizadas (esquistos filoníticos). Se han localizado gabros en la zona de Cuesta del Viento, en la sierra del Tigre y en el cerro Negro de Iglesia. Son rocas plutónicas de textura granuda, con fenocristales de plagioclasa cálcica (andesina casi en el límite con labradorita). Los mafitos están totalmente cloritizados y carbonatizados. Hay abundante carbonatización en las venillas, abundantes opacos idiomorfos y xenomorfos, agregados de cloritas y pequeños agregados de titanitas. Generalmente estas rocas están afectadas por cataclasis.

Por último, se hallan en esta formación cuerpos de rocas ultramáficas, representados por peridotitas y espessartitas. Las primeras son rocas de textura xenomorfa de grano grueso, formadas por olivina totalmente serpentinizada, con escasos remanentes de la misma y cristales de augita fresca, abundantes opacos xenomorfos y abundante titanita, pequeños agregados de talco. Se localizan en la sierra del Tigre y en los Altos del Colorado, intercaladas en las rocas de la Formación Yerba Loca.

Las espessartitas son rocas volcánicas de textura afanítica melanocráticas, compuestas por laminillas de plagioclasa (andesina) y abundantes cristales de augita formando una aparente textura intergranular, con fragmentos de serpentina y algo de biotita pardo verdosa, abundantes opacos xenomorfos, agregados de clorita, abundantes fenocristales de apatita, titanita en grandes masas, en algunos casos se observan agujas de tremolita - actinolita y un mineral intersticial, posiblemente hornblenda basáltica. Afloramientos de estas rocas se encuentran como capas intercaladas entre las rocas basálticas de la parte superior de la Formación Yerba Loca, en los sectores de Cuesta del Viento y la sierra del Tigre.

<div/>
