---
title: "Formación Las Pircas (4c)"
---

<div style="text-align: justify">

## Pórfidos dacíticos, dacitas, riolitas, riodacitas, ignimbritas, aglomerados, tobas.

La Formación Las Pircas fue denominada originalmente como Intrusivo Las Pircas y descripta como una roca subvolcánica. Furque (1962) describió un cuerpo hipabisal (stock) marginado por los ríos Las Leñas al este, Ojos de Agua al oeste y San Francisco al sur y que en su límite norte es cubierto por las efusiones andesíticas más recientes de la cordillera de Olivares. Los componentes principales de este cuerpo son los pórfidos dacíticos y dacitas. Esta descripción corresponde a los afloramientos del intrusivo Las Pircas. Minera TEA (1968) denominó a este cuerpo intrusivo Stock Dacítico de las Niñas Muertas.

La formación está constituida por una alternancia de coladas de riolitas y riodacitas, ignimbritas, aglomerados y tobas de la misma naturaleza. Esta unidad puede correlacionarse con la Formación El Palque (Caballé, 1986). El afloramiento más importante se localiza a cotas superiores a 3700 m s.n

Se extiende en el borde suroriental del cordón de Olivares con un espesor de 1500 m (Rodríguez Fernández et al., 1996). En el cordón de Colangüil se destaca un importante afloramiento de riolitas en el cerro Pata de Indio, que correspondería a esta unidad.

Según Costas (1967), el conjunto eruptivo aflorante en la quebrada de Agua Negra está constituido por mantos de composición predominantemente riodacítica y riolítica, intruidos en parte por algunos cuerpos volcánicos de similar petrografía. Los mantos inclinan con ángulos variables, en general hasta unos 30º hacia el sudeste.

<div/>
