---
title: "Formación El Puntudo (24)"
---

<div style="text-align: justify">

## Conglomerados, brechas, areniscas, calcilutitas, arcilitas calcáreas, piroclastitas, calizas, limolitas.

Se ha denominado Formación El Puntudo a la secuencia aflorante en el extremo sureste de la sierra de La Crucecita, compuesta por sedimentitas continentales que fueron atribuidas al Triásico por Baraldo et al. (1990), teniendo en cuenta aspectos litológicos y relaciones estratigráficas. La secuencia se inicia con un potente banco conglomerádico clasto sostén, con bloques de hasta 70 cm de diámetro, en general subredondeados a redondeados. El color es generalmente pardo violáceo. En cuanto a su composición predominan rocas ígneas y areniscas en menor proporción.

Esta secuencia es granodecreciente y se intercalan cuerpos lenticulares de brechas con clastos subangulosos de cuarzo pobremente clasificados, con gran diferencia en su granulometría, y en menor porcentaje feldespatos subangulosos y fragmentos de rocas volcánicas alterados. La mátrix es arcillosa ferruginosa, con rasgos de fluidalidad.

La secuencia continúa con areniscas y conglomerados fluviales de color amarillento, con estratificación entrecruzada, paleocauces e intercalaciones de arcilitas y arcilitas calcáreas. En la parte media de la serie se intercalan capas de caliza formadas por carbonato micro a criptocristalino con algo de material arcilloso. Se observan cuerpos ovoides de carbonatos y pequeños fragmentos de cuarzo. Los bancos de caliza se intercalan con capas de limolitas y arcilitas de color pardo rojizo y con lentes de grano más grueso y estratificación cruzada. En la parte superior se observa una sección más estratificada, en la que se intercalan areniscas finas, arcilitas, limolitas y calizas con capas de poco espesor de material piroclástico (Figura 10).

El ambiente de depositación es continental fluvial en las secciones inferior y media, y lacustre hacia los términos superiores de la secuencia.

El espesor de la serie es de 280 metros. La relación estratigráfica es, en la base, discordante con rocas posiblemente pérmicas y en el techo, discordante con un conglomerado de edad terciaria.

En función de las características de los materiales que integran el conglomerado y de su posición estratigráfica se la correlaciona con el Grupo Choiyoi. Según la imagen satelital, el color que posee el afloramiento es idéntico al de las rocas del Grupo Rincón Blanco de edad Triásico superior que afloran en la Precordillera Occidental, en el departamento Calingasta.

<div/>
