---
title: "Granito Chita (7a)"
---

<div style="text-align: justify">

## Granitos.

El plutón granítico de Chita forma parte del ciclo magmático neopaleozoico que corresponde al extremo sur del batolito de Colangüil en la Cordillera Frontal (Llambías et al., 1987). Según Sato (1987), es un cuerpo ovalado en planta, de aproximadamente 9 km de largo por 4 km de ancho, que intruye a sedimentitas carboníferas plegadas de la Formación Agua Negra. Las rocas en general presentan textura granosa mediana a gruesa y su composición es esencialmente granítica, con cuarzo, ortosa pertítica, plagioclasa ácida, escasa biotita, fluorita y circón. A través de todo el cuerpo son abundantes las cavidades miarolíticas, tanto a nivel microscópico como macroscópico, llegando en algunos casos a medir hasta varias decenas de cm de diámetro. En su interior hay crecimiento pegmatoide de cuarzo, feldespato potásico y menor cantidad de fluorita y escaso epidoto.

Según estudios de inclusiones fluidas realizadas por Sato (1987), el stock granítico de Chita se ha intruido a una profundidad de 1,3 km. La edad del plutón Chita es de 247 Ma., según Sato y Kawashita (1988).

<div/>
