---
title: "Formación Castaño (4a)"
---

<div style="text-align: justify">

## Areniscas, limolitas, ignimbritas, calizas.

Constituye la parte basal del Grupo Choiyoi y se apoya discordantemente sobre las unidades del Ciclo Gondwánico. La base está constituida por ortoconglomerados polimícticos, a veces heterométricos, con clastos silíceos y carbonatados, plutónicos y más raramente volcánicos, en general redondeados, excepto los clastos calcáreos. Hay aglomerados, tobas y rocas volcánicas de naturaleza andesítica interestratificados. Se menciona la presencia de conglomerados con olistolitos de calizas de la Formación Agua Negra, a veces intercalados con rocas volcanosedimentarias y volcánicas localizados en la quebrada de Las Leñas. En la parte media de la unidad predominan las areniscas y las limonitas con componentes volcánicos, así como rocas volcanosedimentarias y volcánicas (aglomerados, tobas e ignimbritas) y cuerpos de andesitas predominantemente y en menor proporción riodacitas y dacitas. La parte superior contiene calizas negras laminadas con abundantes nódulos de chert, en bancos de hasta 16 m, intercaladas entre vulcanitas. Este sector ha sido diferenciado como Miembro Manrique en la hoja Castaño Viejo (Rodríguez Fernández et al., 1996).

<div/>
