---
title: "Fm. San Ignacio y Agua Negra (1)"
---

<div style="text-align: justify">

## Margas, calizas y lutitas

La Formación San Ignacio fue definida por Rodríguez Fernández et al. (1996). Toma el nombre de la quebrada homónima ubicada al norte de la mina Castaño Viejo.
Los afloramientos de la Formación San Ignacio se restringen a la margen derecha del río Castaño y dados los escasos espesores no se pueden representar en la hoja a escala 1:250.00, de modo que han sido integrados en una sola unidad junto con la Formación Agua Negra de edad carbonífera, si bien entre ambas existe un hiatus que comprende el Carbonífero inferior.

Litológicamente la Formación San Ignacio está constituida por calizas y calizas margosas de color gris claro o crema, entre las que se intercalan delgados niveles lutíticos. La unidad está organizada en secuencias de 2 a 3 m de espesor, compuesta por niveles de litarenitas verdosas en la base con alternancias de calizas bioclásticas que aumentan en frecuencia y espesor hacia arriba. Estos ciclos corresponden a secuencias de somerización típicas de plataformas carbonáticas de aguas someras. Ocasionalmente se encuentran cuerpos litológicos de calizas bioclásticas de geometría planoconvexa, que representan barras de oleaje y corresponden al término más somero de las secuencias. Su espesor real no ha podido medirse debido a que constituyen la superficie de sobrecorrimiento gondwánico más generalizada, su máximo espesor aflorante está entre 25 y 70 m (Rodríguez Fernández et al., 1996). Su edad, sobre la base de esporas recolectadas en los términos margosos, es silúrico - devónica (Pöthe et al., 1987). No se conoce su base, mientras que el techo es discordante con la Formación Agua Negra en la zona de Castaño.

Furque (1962), en la descripción del perfil de la cordillera de Olivares (quebrada de Tocota), describió lutitas y bancos de cuarcitas compactos de un metro de espesor que contienen restos de vegetales del tipo Haplostigma, asignándoles una edad devónica. La secuencia observada comprende además lutitas y cuarcitas de color morado oscuro, grauvacas verdes y capas gruesas de conglomerados. Afloramientos de ésta misma secuencia han sido observados en la confluencia del río San Francisco con el río Ojo de Agua.

Sato (1989) mapeó un afloramiento de rocas sedimentarias de color gris verdoso oscuro como pre Carbonífero, tal vez Devónico, en la quebrada de Chita.

Lutitas, areniscas, conglomerados y calizas
La denominación procede de Polanski (1970) y su localidad tipo se encuentra en la quebrada de Agua Negra. Su edad fue establecida por Aparicio (1969) como carbonífero superior a pérmica inferior.
Son numerosos los antecedentes que se refieren a los depósitos carboníferos en la quebrada Agua Negra. Achen (1948) mencionó la existencia de plantas fósiles de edad carbonífera superior. Groeber (1951) caracterizó a las sedimentitas aflorantes como esquistos arcillosos que culminan con bancos de cuarcitas. Costas (1967) describió una secuencia carbonífera superior constituida por dos secciones: una inferior masiva, gris oscuro, formada por subgrauvacas con limoarcilitas y limolitas con estratificación cruzada y ondulitas; y una superior estratificada y de colores más claros, con alternancias de psamitas y limoarcilitas. Aparicio (1969) citó un yacimiento nuevo de vegetales en la quebrada de Agua Negra (Rhacopteris ovata, Gondwanidium platianium) y un yacimiento de invertebrados marinos, (Cancrinella sp., Orthoceras sp.) con una edad carbonífera superior a pérmica inferior. González (1976) consideró la secuencia sedimentaria neopaleozoica de carácter continental en términos generales, con una ingresión marina en la base. Gutiérrez (1983) realizó perfiles en las quebradas Áspera y de la Tranquita de Abajo, ambas tributarias de la quebrada de Agua Negra, próximas al puesto de Gendarmería, describiendo una predominancia de litología fina con areniscas subordinadas.
Reconoce siete facies y las atribuye a un ambiente mixto y de transición, litoral clástico. Lasecuencia se inicia con un ambiente marino litoral que gradualmente pasa a depósitos continentales de origen fluvial. La edad de la secuencia, según ese autor, es carbonífera superior, sin descartar que pase al Pérmico inferior. Gabaldón et al. (1985) describieron una secuencia de 300 m en las quebradas Áspera y de Agua Negra, formada por ciclos de facies estrato y grano crecientes que por sus estructuras internas corresponderían a ciclos de playa de una plataforma silicoclástica somera, dominada por el oleaje y donde la dinámica mareal sólo a veces ha quedado preservada (Figura 2).
En el cordón de Olivares, quebrada de Las Leñas, Furque (1962) describió una secuencia carbonífera sobre la base de similitudes con las sedimentitas de la quebrada de Agua Negra y por la flora fósil hallada, correspondiente al género Rhacopteris. En este sector la Formación Agua Negra se apoya discordantemente sobre sedimentitas atribuidas al Devónico.
Al sur de la quebrada Agua Negra, en el sector comprendido entre las quebradas Bauchaceta y Tocota, Gabaldón et al. (1985) concluyeron que este sector es análogo al resto del Carbonífero descrito en la quebrada de Agua Negra, formado por lutitas oscuras y areniscas de grano medio a fino. Estas conclusiones se basan en el estudio de detalle de 150 m de perfil en la quebrada de Bauchaceta y 60 m en la quebrada de Tocota.
Limeres (1985) realizó perfiles columnares de las sedimentitas carboníferas en la quebrada de Bauchaceta. Reconoció tres facies que se repiten varias veces a lo largo de los 175 m levantados. La facies A corresponde a un paleoambiente de laguna costera, la facies B a barras arenosas y la facies C a canales que forman parte del ambiente lagunar.
En el sector más al norte de la hoja, Quartino y Zardini (1967) mencionaron la presencia de fangolitas y areniscas de colores grises a negros bien estratificados, como rocas de caja de los intrusivos varíscicos, en la quebrada de Conconta y al norte de ésta. Spikerman (1967) atribuyó un origen lagunar a deltaico a las sedimentitas aflorantes en la quebrada de Los Puentes, basado en el hallazgo de fósiles de agua dulce (pelecípodos) y ciertas estructuras primarias. Nawratil (1983) realizó dos perfiles de detalle, ubicados en la quebrada de Arrequintín y del Kilómetro 94, donde diferenció doce facies sedimentarias sobre la base de los caracteres litológicos, estructuras sedimentarias y contenido paleontológico. De esta manera concluyó que el ambiente de sedimentación de la Formación Agua Negra es un medio de transición, litoral clástico, que pasa gradualmente a depósitos más continentales hacia la parte superior donde se encontraron restos vegetales. Los fósiles hallados le permitieron asignar esta sucesión al Carbonífero superior y Pérmico inferior.
Vitaller (1994) y Charchaflié (1994) describieron rocas similares a las referidas en párrafos anteriores correspondientes a los afloramientos de la Formación Agua Negra en la quebrada de Chita.
Según Rodríguez Fernández et al. (1996), en la región de Castaño la serie puede dividirse en dos conjuntos de características diferentes separados por un nivel de conglomerados: un conjunto inferior formado por lutitas, areniscas y microconglomerados que corresponden a depósitos de plataforma terrígena somera que incluyen barras de mar abierto, secuencias progradantes de playa y depósitos de plataforma abierta, entre los que se encuentran niveles depositados por tormentas; y un conjunto superior que incluye en su base areniscas, lutitas y conglomerados, y en su parte superior calizas organizadas en ciclos de llanura de marea con abundantes restos vegetales, representando depósitos de canales distributarios, lóbulos deltaicos y llanuras deltaicas con una disminución de aporte terrígeno hacia arriba.
En el sector más oriental se encuentran las facies más restringidas del Carbonífero, compuesto por arcilitas, paleocanales de areniscas, limolitas laminadas y capas de carbón, depositadas en ambiente de albúfera, atravesadas por canales distributarios. Estos afloramientos se localizan en Las Timbirimbas, margen izquierda del río Castaño.
Las sedimentitas de la Formación Agua Negra, en el contacto con el granito Conconta, están meta morfizadas e intruidas por numerosos diques. Son rocas de grano fino y de color negro. Al microscopio presentan textura granoblástica con presencia de cristales de cuarzo, plagioclasa, feldespato potásico y biotita. Se intercalan lentes más ricos de mica blanca (sericita). Estas rocas han sido clasificadas en estudios microscópicos como pizarras moteadas y corneanas cuarzo feldespáticas alteradas.

Los afloramientos de la Formación Agua Negra se extienden en el borde oriental de los cordones de Olivares y de Colangüil. En general su base no aflora. En la región de Castaño yace discordantemente sobre la Formación San Ignacio. La potencia de esta secuencia sedimentaria es estimada en el orden de los 2000 m por Polanski (1970); 2500 m por González (1976) y en 3400 m por Limeres (1985) en la quebrada de Bauchaceta. Los mayores espesores se encuentran en el borde oriental del cordón de Olivares.

La relación de la Formación Agua Negra con las rocas infrayacentes ha sido observada en la región de Castaño Viejo por Rodríguez Fernández et al. (1996). La Formación Agua Negra está en discordancia sobre la Formación San Ignacio de edad silúrico-devónica, limitando una laguna estratigráfica que abarcaría la mayor parte del Devónico y el Carbonífero inferior. En la base suele aparecer un ortoconglomerado polimíctico de cantos bien redondeados en el que se destaca la presencia de clastos de rocas metamórficas. El techo de esta unidad está constituido, en la región de Castaño Viejo, por las piroclastitas y vulcanitas del Grupo Choiyoi, de edad permo-triásica.
La Formación Agua Negra se depositó en una cuenca de retroarco (Ramos et al., 1986). El relleno de la cuenca se mantuvo en equilibrio con la subsidencia, predominando en todo su espesor un régimen de aguas someras con influencia del oleaje (Gutiérrez, 1983; Gabaldón et al., 1985).


<div/>


