---
title: "Intrusivos riolíticos (4d)"
---

<div style="text-align: justify">

## Riolitas y dacitas.

Pequeños afloramientos de cuerpos intrusivos que no se pueden representar a la escala de la hoja afloran en la quebrada El Carrizal. Se trata de un conjunto de apófisis riolíticos a dacíticos de reducidas dimensiones. La datación de un cuerpo aflorante ubicado en la quebrada El Volcán, realizada por el método Ar/K sobre roca total arrojó una edad de 261 ± 22 Ma., que permite ubicarlo en el rango comprendido entre el Pérmico inferior y el Triásico medio (Rubinstein, 1992). Esta unidad está vinculada con los yacimientos uraníferos y auríferos de la quebrada El Carrizal.

Rocas de color rosado claro, que han sido clasificadas como dacitas y riolitas, afloran en la sierra de La Crucecita, como diques o stocks pequeños intruyendo lutitas verdes que han sido asignadas tentativamente al Ordovícico. Diques riolíticos y traquíticos intruyen a las filitas del Ordovícico en la sierra Negra. También existen afloramientos de riolitas en las proximidades de la localidad de Buena Esperanza, Angualasto, intruyendo rocas devónicas y carboníferas.

Estos cuerpos riolíticos son rocas de textura porfírica formadas por fenocristales de feldespato, cuarzo y mafitos alterados. El feldespato es en su mayoría ortosa. La matriz es plagioclásica subfluidal a microfelsítica con marcada argilitización.

<div/>
