---
title: "Formación Cerro de Las Tórtolas (11)"
---

<div style="text-align: justify">

## Lavas andesíticas a dacíticas, tobas, aglomerados e ignimbritas

La Formación Cerro de Las Tórtolas fue definida por Maksaev et al. (1984). Es una secuencia de volcanitas andesíticas que sobreyacen en forma discordante a la Formación Doña Ana y unidades más antiguas. En la Hoja Rodeo, la Formación Cerro de Las Tórtolas aflora en las cabeceras del valle del Cura. Los afloramientos de esta formación se localizan en los cerros Carmen y Paso de Las Lagunitas, próximos al volcán Tórtolas. Está integrada por lavas andesíticas a dacíticas color gris oscuro con niveles piroclásticos proximales, brechas volcánicas y tobas más distales. Estas rocas están afectadas por alteración hidrotermal (Figura 4). La secuencia comprende en total unos 1500 m. de espesor.

La edad de la Formación Cerro de Las Tórtolas es miocena inferior a media, dado que dataciones realizadas en el territorio chileno varían entre 16,6 y 11 Ma. Ramos et al. (1987) efectuaron una datación K/Ar (roca total) en una muestra del cerro de Las Tórtolas, obteniendo una edad de 12,8 ± 0,4 Ma., lo que corrobora la edad asignada anteriormente.

En principio, la Formación Cerro de Las Tórtolas se correlaciona con el denominado Grupo Melchor en la región del río Castaño.

<div/>
