---
title: "Grupo Iglesia (26)"
---

<div style="text-align: justify">

## Conglomerados, areniscas, arcilitas e ignimbritas.

Las sedimentitas continentales terciarias de la región fueron denominadas Formación Rodeo por Furque (1963). Posteriormente, Wetten (1975 a y b) definió el Grupo Iglesia para la misma secuencia neógena. Este autor reconoció dos unidades: una inferior denominada Formación Lomas del Campanario y una superior llamada Formación Las Flores. Minera TEA (1968) llamó Formación de Tobas, Brechas y Aglomerados a la Formación Lomas del Campanario, asignándole una edad terciaria superior. Leveratto (1976) realizó dataciones en afloramientos de rocas volcánicas del cerro Negro y Tocota asignándolas al Mioceno inferior a medio.

Johnson et al. (1987) describieron la secuencia terciaria entre Cuesta del Viento y Rodeo y efectuaron un estudio cronológico en estas sedimentitas, a partir de los circones extraídos de las tobas. Beer et al. (1990) consideraron que la sedimentación cenozoica tuvo lugar en una cuenca de piggy back.

Zambrano y Damián (1992) describieron las unidades del Terciario desde un punto de vista hidrogeológico en la zona de Cuesta del Viento. Jordan et al. (1993) realizaron varias dataciones geocronológicas del Terciario. Bercowski (1993) describió las facies piroclásticas del Terciario de Iglesia. Jordan et al. (1997) estudiaron las vinculaciones genéticas entre las cuencas miopliocénicas del valle de Iglesia y del valle de Bermejo.

En la Hoja, secciones aflorantes al este y norte de Rodeo y en la sierra Negra fueron mapeadas como Grupo Iglesia sensu lato, al no haberse podido discriminar las unidades formacionales que lo integran.

<div/>
