---
title: "Afloramientos Intrusivos terciarios Cordillera Frontal
 Intrusivos terciarios Precordillera"
---

<div style="text-align: justify">

## Andesitas, dacitas y riodacitas.

Afloramientos de rocas subvolcánicas andesíticas terciarias se localizan entre los arroyos Tocota y Espota. Al sur de Tocota, Leveratto (1976) describió una dacita lamprobolítica gris pardusca, rosada. Esta roca fue datada mediante el método K/ Ar y dio una edad de 18,3 ± 2,5 Ma., correspondiente al Mioceno inferior. Otros cuerpos andesíticos y riodacíticos pequeños se localizan en el arroyo de Chita. Afloramientos en el borde oriental del cordón de Olivares (arroyo de Chita) han sido clasificados como andesitas. Son rocas de textura porfírica con abundantes cristales de plagioclasa y mafitos en una mátrix felsítica. El cuarzo es escaso, con estructura de engolfamiento; el mafito es hornblenda transformada en biotita parda cloritizada. Todos los fenocristales poseen bordes de reacción con la pasta. Presenta abundantes idiomorfos de sección cúbica en la pasta.

Relacionados con la zona de alteración de La Poposa y estructuras de caldera, existen algunos afloramientos de andesitas y riodacitas.

Al oeste del valle de Los Patos, en el límite con Chile, afloran pequeños cuerpos de edad terciaria que en la Hoja Pisco de Elqui (Chile) han sido denominados como Unidad Infiernillo (Maksaev et al., 1984). Se trata de pequeños stocks en su mayoría pórfidos andesíticos y dioritas cuarcíferas de grano fino. Mediante el método K/Ar se han datado diferentes rocas de esta unidad en el territorio chileno obteniéndose resultados que van desde 16,0 ± 2 Ma. a 17,7 ± 0,7 Ma. (Mioceno inferior).

## Andesitas y dacitas.

Leveratto (1976) describió afloramientos de cuerpos andesíticos y dacíticos en el cerro Negro de Iglesia y próximos al sur de la localidad de Tocota. En el primer lugar el autor mencionado describe las rocas como dacitas horblendobiotíticas de color gris claro a gris blanquecino, macizas, con fenocristales de plagioclasa, hornblenda, biotita y cuarzo en una pasta andesítica.
En Tocota, Leveratto (1976) describió dos masas dacíticas que son interpretadas como intrusivos por su estructura interna. Se trata de una dacita lamprobolítica, maciza y gris pardusco a rosada. Las muestras obtenidas en distintos afloramientos de ésta unidad han sido clasificadas en general como andesitas. Son rocas compactas de textura porfírica con fenocristales de feldespato blanco lechoso y mafitos aciculares en una matriz afanítica de color gris claro. Los mafitos corresponden a hornblenda pardo verdosa.

Estos cuerpos fueron datados mediante el método K/Ar (Leveratto, 1976) y los resultados arrojaron una edad de 17 ± 5 Ma. para los afloramientos del cerro Negro y 18,3 ± 2,5 Ma. para los cuerpos de Tocota, correspondientes al Mioceno inferior a medio.

<div/>
