---
title: "Granito Conconta (6)"
---

<div style="text-align: justify">

## Granitos.

La denominación Granito Conconta fue dada por Quartino y Zardini (1967) para el granito que aflora en la quebrada homónima, cubriendo un área de unos 40 km2 al este de la Granodiorita.
Castro (1991) diferenció texturalmente dos facies: una de grano mediano a grueso (2 a 6 mm) y otra microgranítica (0,9 mm). 

La primera está caracterizada por rocas rosadas parcialmente rojizas y amarillentas con textura hipidiodomorfa y compuesta por cuarzo (30%), feldespato potásico (40%), plagioclasas (24%) y biotita (6%). Los individuos de cuarzo son subidiomorfos con microfracturas rellenas por moscovita y óxidos de hierro. La facies microgranítica constituye las rocas de grano fino que afloran en forma de fajas dentro del granito. La textura es granular alotriomorfa, con cuarzo anhedral (35%), feldespato potásico micropertítico (48%), plagioclasas (4%) y biotita (3 %).

El Granito Conconta está intruido por un enjambre de diques de composición ácida, que por ser considerados comagmáticos se describen con esta unidad. Están representados por pórfidos graníticos y riolíticos, riolitas y dacitas. Además, conjuntamente con ellos se intruyeron diques básicos a intermedios compuestos por. pórfidos andesíticos.

El Granito Conconta intruye a la Granodiorita Romo (Figura 3). Este dato está confirmado por las dataciones absolutas por el método Rb/Sr para el Granito Los Puentes (homólogo al Granito Conconta) de 257 - 249 Ma. efectuadas por Shaw et al. (1990).

<div/>
