---
title: "Formación Punilla (21a)"
---

<div style="text-align: justify">

## Cuarcitas, areniscas, lutitas, conglomerados.

El nombre de Formación Punilla fue dado por Furque (1963), durante el levantamiento de la Hoja 17b, Guandacol, a las sedimentitas devónicas que conforman la sierra de la Punilla. En el ámbito de la Hoja Rodeo afloran al este de Angualasto, constituyendo un cordón que se extiende desde el cerro Negro hacia el norte. Los límites occidental y oriental están constituidos por fallas, de modo que no se conocen la base ni el techo de la unidad.

La Formación Punilla está constituida por cuarcitas y areniscas finas compactas de color gris, bien estratificadas, en bancos no superiores a un metro. Estas cuarcitas alternan con lutitas de color gris negruzco, portadoras de restos vegetales mal conservados. Se intercalan capas de conglomerados gruesos con clastos de cuarcitas (Furque, 1963).

Baldis y Sarudianski (1975) interpretaron que las unidades del Devónico en las sierras del Volcán y La Punilla se formaron en un flanco de plataforma abierta móvil, cerca de la línea de costa. La presencia de depósitos turbidíticos asociados a flujos gravitatorios se interpretan como depósitos de abanico distal o la parte externa de abanico medio con procedencia del este (Sessarego, 1988).

En las capas superiores del conjunto, en afloramientos de las quebradas Los Acerillos, Vega Chica, Carrizalito y Quebrada Larga, en la Hoja 17b, se han reconocido ejemplares de Haplostigma sp., Hostimella sp., Ateroxilon sp. y Adiantites sp, los cuales han sido considerados por Frengüelli (1952) como pertenecientes a un Devónico medio alto, que podría extenderse al Devónico superior. Según Furque (1963), el espesor máximo alcanza 4000 metros. En la Hoja Rodeo se calcula que el espesor de esta unidad es de 500 metros.
<div/>
