---
title: "Formación La Invernada & Yerba Loca (20)"
---

<div style="text-align: justify">

## Cuarcitas, lutitas, areniscas, calizas, conglomerados.

La Formación La Invernada fue denominada por Furque (1983). Su nombre proviene de la sierra de La Invernada. Sus relaciones de base y techo son desconocidas, dado sus contactos por falla. El perfil tipo fue realizado en la quebrada del cerro Bayo, en donde se midió una potencia de 1200 metros. Furque (1983) reconoció cuatro miembros. Los inferiores están compuestos por alternancias de cuarcitas, subgrauvacas y filitas de color verde claro grano y estratocrecientes. El miembro cuarcítico medio contiene un banco de conglomerados en su techo, con clastos de calizas grises de la Formación San Juan. El miembro superior consiste en una alternancia de cuarcitas y calizas en estratos crecientes, que van de 5 cm hasta 1,5 m. En los niveles superiores se trata de una caliza conglomerádica. Están intruidas por cuerpos filonianos basálticos que han metamorfizado a las sedimentitas calcáreas en sus contactos. Se ha constatado la presencia de pirita en las calizas del miembro superior. La presencia de conglomerados con clastos de calizas de la Formación San Juan permite inferir que la Formación La Invernada es posterior, estableciéndose así un límite inferior. Por otro lado, los miembros de la Formación La Invernada están afectados por una actividad magmática similar a la que intruye a la Formación Yerba Loca. Esto nos daría el límite superior. Así, se puede establecer la edad de la Formación La Invernada como Caradociano sensu lato, sobre la base de que sus características son similares a las de la Formación Yerba Loca, datada por contener restos de graptofauna, y considerando que posee una posición inferior a aquella (Furque 1983). Furque y Caballé (1985), al analizar la geología del cerro Bayo de La Invernada, le dieron a la Formación La Invernada una edad caradociana temprana, sobre la base de descripciones litológicas. Posteriormente, el hallazgo de graptolites del Ordovícico confirmó la edad de esta unidad, lo cual determinó un nuevo ordenamiento estratigráfico (Furque y Caballé, 1988). Furque et al. (1990) dieron a conocer una graptaofauna del Llandeillano - Caradociano, correspondiente a niveles fosilíferos en la quebrada Vallecito, que luego fueron corroborados por nuevos hallazgos fosilíferos (Caballé et al., 1992).

Las características litofaciales de las sedimentitas ordovícicas de la sierra de La Invernada fueron analizadas por Banchig (1995), quién identificó cinco litofacies a lo largo de toda la sierra: conglomerados, areniscas, lutitas y areniscas finas, carbonatos y brechas carbonáticas, correspondientes a una sedimentación asociada a sistemas de abanicos submarinos cuyo mecanismo sedimentario fueron las corrientes de turbidez (Banchig, 1995, 1996).

## Lutitas, areniscas, conglomerados, basaltos, pillow lavas.

La Formación Yerba Loca fue creada por Furque (1963) para designar un conjunto de sedimentitas marinas, desde conglomerados a lutitas, asignadas al Ordovícico. La localidad tipo se halla en la sierra que le da nombre, en el norte de la Precordillera Occidental. Si bien originalmente los cuerpos de rocas básicas intercalados o que intruyen a estas sedimentitas no fueron incluidos en esta formación, desde la interpretación de Borrello (1968, 1969) de su carácter ofiolítico, son consideradas como parte de la misma.

Esta unidad se extiende en la sierra del Tigre, cerro Alto del Colorado, cordón del Coronel, cerro Negro de Iglesia y en Cuesta del Viento (Furque, 1983).

Furque (1983) describió en el cordón del Coronel, un perfil de 500 m de espesor, cuya base comienza con subgrauvacas grises a verdosas, luego le siguen areniscas cuarcíticas intercaladas con lutitas laminadas, mientras que un último banco está constituido por lutitas pizarrosas, cuarcíticas. Este termina interrumpido por falla en el borde occidental de dicho cordón.

En la sierra del Tigre se distingue un conjunto que comienza con lutitas blancas a grises claro, laminadas, afectadas por la intrusión de cuerpos ígneos básicos, que en el contacto forman rocas corneanas (Figura 5). Su espesor es de aproximadamente 150 metros. Luego siguen areniscas finas compactas a subgrauvacas que alternan con bancos delgados de lutitas, constituyendo un espesor de 300 metros. Suprayaciendo a éstas afloran areniscas cuarcíticas finas, intruidas por numerosos diques y filones capa de lavas almohadilladas conformando un total de 250 m de espesor. La secuencia termina con lutitas gris claro a oscuro, laminadas, que se caracterizan por poseer niveles de lavas almohadilladas. Su espesor es de 200 metros. Sus contactos, tanto superior como inferior, son por falla, por lo que se desconoce su techo y base.

El ambiente de sedimentación es marino de mediana a baja energía. Según Furque (1982), las sedimentitas de las formaciones La Invernada y Yerba Loca corresponden a un paleoambiente marino de zona sublitoral distal de una región epibatial. Los niveles conglomerádicos son manifestaciones episódicas de un proceso de resedimentación producto de breves oscilaciones de la cuenca sedimentaria. Se pueden contar cinco ciclos constituidos por una sucesión de wackes, conglomerados, wackes y pelitas, que comienzan con una sucesión grano creciente y terminan con una decreciente.

Blasco y Ramos (1976) dieron a conocer una localidad fosilífera de la Formación Yerba Loca en las cercanías de Cuesta del Viento, donde se ha hallado una fauna de graptolites (Nemagraptus gracilis) que indicarían edad caradociana inferior.

Beresi (1990) incluyó a la Formación Yerba Loca en el segundo ciclo de sedimentación ordovícica, denominado ciclo clástico del Llanvirniano al Caradociano basal, constituido por una secuencia turbidítica de alta densidad, muy diluida y sedimentación pelágica que corresponde a los sectores más distales de la cuenca. Está asociada a volcanismo submarino y afectada por un metamorfismo dinámico. El paleoambiente corresponde a talud y cuenca profunda (Pereyra, 1989).

<div/>
