---
title: "Formación Doña Ana (9)"
---

<div style="text-align: justify">

##Ignimbritas y tobas riolíticas y dacíticas.

La Formación Doña Ana ha sido definida en territorio chileno, en la cordillera de Doña Ana (Maksaev et al., 1984). Se reconocen dos miembros, uno inferior: Miembro Tilito y uno superior: Miembro Escabroso. En el territorio argentino aflora solamente el miembro inferior, compuesto por ignimbritas y tobas riolíticas y dacíticas. Los afloramientos se distribuyen al sur del paso de Agua Negra, en la cordillera de Olivares y en el valle del Cura. La Formación Doña Ana aflora en el curso inferior del arroyo de las Cabeceras del Valle del Cura y en los arroyos Carmen Sur y Carmen Norte, cerca de la confluencia con el valle. La potencia de esta unidad es de unos 1.000 m en el paso de Agua Negra.

La Formación Doña Ana se dispone en forma discordante sobre las vulcanitas del Grupo Choiyoi y es cubierta también discordantemente por la Formación Cerro de Las Tórtolas.

Sobre la base de numerosas dataciones realizadas en territorio chileno, la edad de la Formación Doña Ana se sitúa entre 27 y 18,9 Ma., es decir entre el Oligoceno superior y el Mioceno inferior.

<div/>
