---
title: "Depósitos lacustres (28)"
---

<div style="text-align: justify">

## Limos, arcillas, arenas, diatomitas.

Los afloramientos de depósitos cuaternarios de origen lacustre fueron descriptos por Wetten (1975 a y b). Se extienden a lo largo del curso de los arroyos Tocota, Iglesia y Colola, desde la localidad de Bella Vista en el sur hasta la confluencia con el río Blanco, y en ambas márgenes del citado río. Son depósitos de granulometría fina (limos, arcillas y arenas finas) de color castaño claro, medianamente compactos y poseen restos de gasterópodos de agua dulce. Esta sucesión alcanza potencias del orden de los 30 metros. En la localidad de Zonda se la puede observar en discordancia sobre la Formación Lomas del Campanario. De su distribución areal se desprende que constituyen un nivel de base transitorio cuando aún no se producía la captura del valle de Iglesia por parte del río Jáchal.

También se describen en esta unidad depósitos de diatomeas que se localizan en mantos subhorizontales que se intercalan con limos, que en algunos sectores cambian de facies arenosa a arcilla compacta. Dichos limos son portadores, en escasa cantidad, de esqueletos opalinos de diatomeas, con presencia de líticos, vidrio volcánico, plagioclasas, hornblenda, biotita, cuarzo y restos de vegetales (Figura 13). El ambiente de formación es lacustre. Estos depósitos se apoyan discordantemente sobre sedimentitas del Terciario.

Los fósiles, en el sector de la localidad de Zonda, se han determinado como Cocconeis sp., Mastoglia sp., Dentícula sp., Caloneis sp., Cyclotella sp., y Amphora sp., mientras que al sur del cerro Negro de Iglesia se han determinado Dentícula sp. y Navícula sp.
El espesor de los mantos de diatomeas es de 10 cm a 5 metros.

<div/>
