---
title: "Formación Lomas del Campanario (26a)"
---

<div style="text-align: justify">

## Ignimbritas, andesitas, tobas, aglomerados, conglomerados, areniscas.

La Formación Lomas del Campanario aflora en las partes bajas del valle de Iglesia, ocupando una faja de 3,5 km. en sentido este - oeste, desde el flanco occidental del cerro Negro de Iglesia en el sur hasta Cuesta del Viento y Angualasto por el norte. Al sur de la localidad de Tocota aflora una secuencia litológica similar, aunque proveniente de centros efusivos diferentes, asignándosela a esta unidad.

La Formación Lomas del Campanario, según Wetten (1975 a y b), está compuesta por una facies inferior aglomerádica, constituida por andesitas, dacitas, tobas y bombas volcánicas de color marrón rojizo, verde grisáceo o gris, y una facies superior conglomerádica, con estratificación cruzada e intercalaciones de diatomitas.

Su espesor es de 950 m y el perfil tipo ha sido reconstruido en Lomas del Campanario. Localmente se observan discontinuidades entre las distintas unidades.
Bercowski (1993) describió las facies piroclásticas del Terciario de Iglesia en tres regiones principales: Cuesta del Viento, Lomas del Campanario e Iglesia

En el sector Lomas del Campanario describió facies de avalancha volcánica de detritos que consiste en un material mal seleccionado, desde cenizas volcánicas hasta grandes bloques, angulosos a muy angulosos, posible producto de la destrucción parcial de un edificio volcánico. Sugirió como un posible centro efusivo el cerro Negro de Iglesia, dada la presencia de depósitos tipo lahar al oeste de dicho cerro, con bloques de 50 a 40 cm y fragmentos líticos volcánicos de 4 a 12 cm, con una disposición caótica; estructura circular del mencionado cerro y la presencia de bombas y bloques a una distancia no mayor de 2 km del centro.

El miembro conglomerádico superior es de carácter poligénico, pero con un alto contenido de vulcanitas. Los clastos son de andesitas, grauvacas, filitas, cuarcitas y otros. Constituye una variación facial del miembro anterior, con el que en algunos casos se interdigita. También integran esta secuencia areniscas grises claro, tobáceas, gruesas a conglomerádicas, con estratificación entrecruzada, cuyo ambiente es fluvial con aporte piroclástico.
Según Zambrano y Damiani (1992), el miembro conglomerádico inferior de la Formación Las Flores correspondería en realidad al miembro inferior de la Formación Lomas del Campanario y de esta manera la Formación Las Flores quedaría restringida a la secuencia pelítica que Wetten (1975 a y b) denominara miembro superior de la Formación Las Flores. En el mapeo de la Hoja se ha seguido este criterio.

Los depósitos volcaniclásticos de la Formación Lomas del Campanario son asignados al Mioceno por estar relacionados genéticamente con los intrusivos andesíticos aflorantes en el cerro Negro de Iglesia y en Tocota, datados por Leveratto (1976) como de edad miocena inferior a media.

<div/>
