---
title: "Formación Corralitos (21)"
---

<div style="text-align: justify">

## Lutitas, areniscas, brechas carbonáticas, calizas y olistolitos de calizas.

La denominación Formación Corralitos fue dada por Furque et al. (1990) y asignada al Ordovícico.Banchig (1995) mencionó el primer hallazgo de fauna fósil de edad silúrica para dicha formación. En descripciones de la hoja Ciénaga de Gualilán, Furque (1983) incluyó a las rocas que la integran como un miembro de la Formación Talacasto (Padula et al., 1967). El espesor es de 150 metros. En la hoja, la Formación Corralitos es discordante sobre la Formación San Juan y está cubierta por los depósitos cuaternarios de la Formación Iglesia. En otros sectores de la Precordillera, su relación es transicional con las formaciones devónicas Talacasto y Punta Negra. Los afloramientos se distribuyen en el flanco oriental de la sierra de La Invernada y hacia el norte en el cordón del Peñón.

Litológicamente, la Formación Corralitos está compuesta por lutitas, areniscas finas a gruesas, brechas carbonáticas y calizas. Particularmente se destaca por la presencia de grandes bloques carbonáticos (olistolitos) cuyas dimensiones superan los 100 m de longitud, con contenidos fosilíferos y características litológicas correspondientes a la Formación San Juan (Figura 8).
En la denominada quebrada de Vallecito, en loma de Los Pozos, Pittaluga et al. (1996) describieron seis litofacies correspondientes a un paleoambiente de plataforma y talud: flujos turbidíticos distales, depósitos turbidíticos distales y depósitos más gruesos de canales distributarios, litofacies de brechas carbonáticas compuestas por bloques carbonáticos angulosos inmersos en una mátrix silicoclástica, facies de olistolitos y depósitos de desmoronamiento y litofacies de grainstones.

Si bien se hallaron fósiles del Silúrico, la relación de transición con unidades devónicas lleva a darle edad silúrico – devónica a esta unidad.

<div/>
