---
title: "Granodiorita de Las Vizcachas (8)"
---

<div style="text-align: justify">

## Granodioritas.

Definida por Minera TEA (1968), la Grano- diorita de Las Vizcachas es un cuerpo ígneo elongado en sentido norte - sur constituido predominantemente por plagioclasa, biotita, cuarzo, con menor presencia de anfíbol y feldespato potásico. El tamaño del grano es mediano a grueso, con facies de tamaño de grano más fino, de composición tonalítica. Presenta enclaves microgranudos de composición más básica. Está intruida por diques de composición basáltica, dacítica y riodacítica. 

Intruye a depósitos del Grupo Choiyoi y es cubierta en forma discordante por depósitos terciarios del Grupo Melchor. Una datación K/Ar obtenida en el INGEIS ha proporcionado una edad de 200 ± 7 Ma. (Jurásico inferior). Representan un evento magmático más reciente que el de los granitos y granodioritas del batolito de Colangüil (Rodríguez Fernández et al., 1996). Aflora en el río Atutia, al oeste de la desembocadura del arroyo Guanaquero. Se extiende a lo largo de las quebradas de Los Avestruces y Las Vizcachas. Hacia el norte sus afloramientos se distribuyen en forma aislada hasta el río San Francisco.

<div/>
