---
title: "Grupo Melchor (14)"
---

<div style="text-align: justify">

## Basaltos, andesitas, dacitas y riolitas. Tobas, lapillitas, ignimbritas, conglomerados, areniscas, calizas.

En el área abarcada en la Hoja Castaño Viejo y el sector adyacente al oeste, zona que comprende la cuenca del río Atutia hasta el valle de Los Patos Norte, afloran unos 1500 a 2000 m de tobas, aglomerados y volcanitas de colores rojos a blancos, con coladas de riolitas intercaladas, que han sido denominadas Grupo Melchor por Rodríguez Fernández et al. (1996).
El Grupo Melchor se compone litológicamente de una parte basal de carácter netamente volcánico, que en la Hoja Castaño Viejo ha sido denominada Formación Puntas Negras, y de una parte superior sedimentaria denominada Formación Río Mondaca.

Entre las vulcanitas se diferenciaron basaltos, andesitas, dacitas y riolitas, tobas basandesíticas, tobas andesíticas y riodacíticas, lapillitas e ignimbritas.
La Formación Río Mondaca está compuesta por conglomerados y areniscas de color rojizo con intercalaciones de algunos niveles de calizas lacustres que han sido depositadas en ambientes de abanicos subaéreos. Posee una potencia de 800 metros. Minera TEA (1968) definió dos unidades de edad terciaria para la zona de la Alta Cordillera que serían equivalentes al Grupo Melchor: a) Serie Volcánica (riolitas, dacitas y andesitas) y b) Formación de las Brechas y Conglomerados. En la Serie Volcánica predominan las coladas riolíticas y andesíticas que se intercalan entre las tobas, brechas y conglomerados. Los afloramientos de esta unidad han sido observados al oeste del río San Francisco y en las cabeceras del arroyo Chita. 

También mencionan afloramientos de éste ciclo efusivo en la zona baja del valle de Iglesia y en el Alto de La Crucecita. La Formación Brechas y Conglomerados aflora en la quebrada de Las Cortaderas (río San Francisco) en donde se dispone en mantos que inclinan unos 30º al sureste. Esta serie presenta filones capa de basaltos intercalados. Hacia el norte de la quebrada de Las Cortaderas resulta el elemento litológico más importante y ocupa normalmente los dos tercios superiores de las serranías y cordones que bordean las quebradas más profundas, como las de los arroyos de la quebrada de Olivares, Ojos de Agua, San Lorenzo y San Francisco Viejo. Casi siempre se presentan infrayaciendo a los basaltos del Grupo Olivares. Los afloramientos se extienden hasta desaparecer en el curso inferior del arroyo Ojos de Agua, siendo reemplazados en el área sureste por el stock dacítico de las Niñas Muertas (Formación Las Pircas) y por la cubierta de los basaltos del Grupo Olivares.
El Grupo Melchor se sitúa discordante sobre el Grupo Choiyoi y levemente discordante sobre la Formación Vizcachas. Una datación realizada en la Hoja Castaño Viejo en una muestra situada en la parte medio alta de esta unidad reveló una edad K/Ar de 15,6 ± 1,29 Ma. Es decir que la edad se extiende desde el Mioceno inferior hasta el Mioceno medio.

Hacia el norte los afloramientos terciarios se extienden en la región de Valle del Cura, donde han sido diferenciados como Formación Doña Ana y Formación Cerro de Las Tórtolas.


<div/>