---
title: "Granito Agua Negra (7b)"
---

<div style="text-align: justify">

## Granitos y granodioritas.

Quartino y Zardini (1967) describieron los afloramientos del batolito de Colangüil en la quebrada de Agua Negra como correspondientes a dos tipos litológicos distintos: una granodiorita hornblendo - biotítica y un granito con biotita rico en ortosa.

Según Costas (1967), el plutón granodiorítico de Agua Negra está constituido predominantemente por granodioritas anfibólico - biotíticas, con granitos y leucogranitos subordinados. La abundancia de miarolas indica cristalización a baja profundidad. Un cuerpo de riodacitas se señala como intrusivo pregranítico, ya que presenta metamorfismo térmico en el contacto con la granodiorita.
La granodiorita posee xenolitos y diques intruidos en el plutón (aplitas y microgranitos)
El plutón Agua Negra tiene forma alargada con orientación NO. Aflora en una extensión de 4 km por 2 km de ancho. Intruye a las sedimentitas de la Formación Agua Negra.

No se han efectuado dataciones de las rocas de este plutón. Las facies granodioríticas serían correlacionables con la Granodiorita Las Piedritas (Satoet al., 1990) mientras que las facies graníticas, dadas sus condiciones superficiales, corresponderían a los granitos de Chita y Agua Blanca.

<div/>
