---
title: "Conglomerados y areniscas fluviales (25)"
---

<div style="text-align: justify">

## Conglomerados, areniscas y areniscas conglomerádicas.

Se reconoce en la zona de la quebrada El Puntudo un conglomerado compuesto por clastos redondeados de composición ígnea proveniente de Cordillera Frontal, que pasa gradualmente a areniscas rojas fluviales. El espesor total de esta secuencia es de 180 metros y se apoya discordantemente sobre las sedimentitas de la Formación El Puntudo, mientras que la relación en el techo es en contacto por falla inversa con rocas paleozoicas.

Teniendo en cuenta la fuerte inclinación de los estratos, la composición que indica un aporte netamente predominante de Cordillera Frontal y las diferencias con los otros depósitos terciarios miocenos con abundantes aportes de material volcánico, se asigna tentativamente estos afloramientos al Paleógeno.

La base está integrada por un conglomerado de color gris con clastos redondeados y de tamaño uniforme de rocas plutónicas y volcánicas, clastos de cuarzo blanco de unos 20 cm de diámetro y en menor proporción clastos de areniscas verdosas. La proporción de clastos es mayor que la mátrix. Se intercalan lentes de areniscas. La secuencia es en general grano decreciente.
Siguen hacia arriba areniscas fluviales amarillentas con estratificación cruzada, lentes conglomerádicos, paleocauces, etc. y más arriba areniscas conglomerádicas de color rojo ladrillo con estratificación cruzada y presencia de paleocanales.

<div/>
