---
title: "Hoja Geológica 3169-I Rodeo"
---

<div style="text-align: justify">

La región estudiada comprende de oeste a este: la Cordillera Frontal, la depresión del valle de Iglesia y el sector occidental de la Precordillera sanjuanina. La Cordillera Frontal está integrada por una secuencia sedimentaria paleozoica media a superior, afectada por una tectónica epidérmica del ciclo Gondwánico, que constituye el basamento; depósitos volcaniclásticos mesozoicos correspondientes a una estructura extensional permotriásica y las secuencias volcaniclásticas terciarias sinorogénicas afectadas por la etapa compresiva del Ciclo Ándico, el cual invierte parcialmente la tectónica extensional. La cuenca de Iglesia, perteneciente a la depresión Rodeo - Uspallata y localizada entre las provincias geológicas de Cordillera Frontal y Precordillera, está rellenada por depósitos terciarios sedimentarios y piroclásticos y sedimentos cuaternarios. Constituye una típica cuenca transportada (piggy back basin). La Precordillera está integrada por una secuencia sedimentaria marina del Paleozoico inferior que culmina con una serie ofiolítica; secuencias de menor extensión de sedimentitas marinas y continentales del Paleozoico medio a superior; una secuencia mesozoica de naturaleza piroclástica y fluvial restringida a pequeños afloramientos; y depósitos volcaniclásticos sinorogénicos terciarios. La tectónica que ha modelado la forma actual de la Precordillera corresponde al Ciclo Ándico en su eta pa compresiva. Es una estructura imbricada con fallas de rumbo norte - sur, con vergencia al este. Existen además estructuras que son asignadas a una tectónica preándica (Ciclo Famatiniano). En el ámbito de la hoja se distinguen tres regiones geomorfológicas: Cordillera Frontal, valle de Iglesia y Precordillera. Las geoformas de la Cordillera Frontal son el resultado de la acción de los procesos glaciario y periglaciario, fluvial, volcánico y eólico con un fuerte control estructural. En el valle de Iglesia predominan las bajadas pedemontanas. Los cordones y valles de la Precordillera, de orientación norte – sur, han sido determinados por una estructura de faja plegada y corrida producida durante el ciclo Ándico. Los principales yacimientos metalíferos se distribuyen en Cordillera Frontal. Se destacan manifestaciones de plomo, plata, cinc, cobre y oro, oro y arsénico, hierro, wolframio y molibdeno. En la Precordillera y en el valle de Iglesia hay depósitos de arcillas, sulfato de sodio, yeso y diatomeas. Los principales sitios de interés geológico destacados en la hoja son los siguientes: 1) Pillow lavas y basaltos columnares de Cuesta del Viento, 2) falla del Tigre, 3) depósitos carboníferos de la quebrada de Agua Negra, 4) mina San Francisco de los Andes, 5) batolito de Colangüil, 6) valle del Cura, 7) distrito polimetálico Castaño Viejo, 8) depósitos piroclásticos de Tocota, 9) pórfido de Chita y 10) valle de Los Patos.
CARDÓ, R., I.N.DÍAZ, M. CEGARRA, N. HEREDIA, R. RODRÍGUEZ FERNÁNDEZ y G. SANTAMARÍA, 2005. Hoja Geológoca 3169-I, Rodeo. Provincia de San Juan. Instituto de Geología y Recursos Minerales. Servicio Geológico Minero Argentino. Boletín 272, 47 p. Buenos Aires.
Fil: Cardó, Raúl. Ministerio de Planificación Federal, Inversión Pública y Servicios. Secretaría de Minería. Servicio Geológico Minero Argentino (SEGEMAR); Argentina.

[acceso al repositorio](https://repositorio.segemar.gob.ar/handle/308849217/173)

<div/>


<div style="text-align: center">

Díaz, Iris Nancy. Ministerio de Planificación Federal, Inversión Pública y Servicios. Secretaría de Minería. Servicio Geológico Minero Argentino (SEGEMAR); Argentina.

Cegarra, Marcelo. Ministerio de Planificación Federal, Inversión Pública y Servicios. Secretaría de Minería. Servicio Geológico Minero Argentino (SEGEMAR); Argentina.

 Heredia Carballo, Nemesio. Ministerio de Planificación Federal, Inversión Pública y Servicios. Secretaría de Minería. Servicio Geológico Minero Argentino (SEGEMAR); Argentina.

Rodríguez Fernández, Roberto. Ministerio de Planificación Federal, Inversión Pública y Servicios. Secretaría de Minería. Servicio Geológico Minero Argentino (SEGEMAR); Argentina.

Santamaría, Graciela R. Ministerio de Planificación Federal, Inversión Pública y Servicios. Secretaría de Minería. Servicio Geológico Minero Argentino (SEGEMAR); Argentina.

Fauqué, Luis A. Ministerio de Planificación Federal, Inversión Pública y Servicios. Secretaría de Minería. Servicio Geológico Minero Argentino (SEGEMAR); Argentina.


<div/>

